name: stereoview
channels:
  - conda-forge
  - defaults
  # stablediffusion
  - pytorch
dependencies:
  - python=3.10
  - pip
  # stablediffusion
  - cudatoolkit=11.8.0
  - pytorch=2.9.1
  - torchvision=0.24
  - numpy=1.24.3
  - pip:
    - peft==0.17.1
    - tqdm==4.67.1
    - opencv-python==4.12.0.88
    - diffusers==0.35.2
    - transformers==4.57.1
    - accelerate==1.11.0
    - safetensors==0.6.2
    - mathutils==3.3.0
    - pandas==2.3.3
    - matplotlib==3.10.7
    - tueplots==0.2.1
    # stereodiffusion
    - ftfy==6.3.1
    - ipywidgets==8.1.8
    # stablediffusion
    - albumentations==1.3.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2 # has to be < version 2.0 bc of zero123 train
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit==1.12.1
    - streamlit-drawable-canvas==0.8.0
    - einops==0.3.0
    - webdataset==0.2.5
    - kornia==0.6
    - open_clip_torch==2.0.2
    - invisible-watermark==0.2.0
    - torchmetrics==0.6.0
    - -e .
    # DPT
    - timm==0.4.5
    # prompt-to-prompt
    # - nothing to add
    # zero123 train
    - --extra-index-url https://download.pytorch.org/whl/cu130
    - carvekit-colab==4.1.2
    - pudb==2025.1.5
    - torch-fidelity==0.3.0
    - fire==0.7.1
    - datasets[vision]==4.4.2
    - rich
    - lovely-numpy==0.2.18
    - lovely-tensors==0.1.20
    - plotly==6.5.0
    - taming-transformers==0.0.1
    - openai-clip==1.0.1
    - requests==2.32.5
    - scipy==1.15.2

